# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0278e14c17d2b5fbc5a41abaf3f4a38c4e593a9201a5963d9575d2debe3f9b5950bb1dcfed99b0328d5f3c68b05c3a5bf94f942ef1316dbfc95dd190cd34f345

test:
  secret_key_base: 41df65bff048d9960bcc1d59e90dd481f34cc6c1ea36dd5d9552b2cb00f259e883c4cf74ff952b13af481ad0afbb38d3d657f83b73e6c83fc587f0251a88d725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
